language: python

python:
  - 2.7

sudo: required

services:
  - postgresql

before_script:
  - psql -c 'create database travisci;' -U postgres
  - python manage.py migrate

install:
  - pip install -r requirements.txt
  - apt-get install build-dep python-psycopg2
  - pip install psycopg2
